"""
(c) 2017 JUSTYN CHAYKOWSKI
PROVIDED UNDER MIT LICENSE

SCHOOLOGY.COM
ACCESS CODE: GNH9N-KZ2C2


RIC 115 <-- OFFICE HOURS:
M 4-6 PM
W 12-6 PM

##########################################
# RICE LAB
#
# TEXT BOOK = ARDX ARDUINO EXPERIMENTER'S KIT - OOMLOUT
#
# CLASS PROJECT --MUST-- BUILD OFF OF WORK ALREADY DONE BY OTHER PEOPLE
#
# CTECH MAKER SPACE UNDER RIDDELL !!!!
##########################################

'FIRST FINAL EXAM QUESTION':
 - SEE THE TOPICS MAP PROVIDED "TOPIC_MAP_EXAMQ_1_2.JPG"

HACKER:
A MORE LEGITIMATE DEFINITION: "SOMEONE WHO MAKES A DEVICE DO SOMETHING OTHER
THAN IT WAS ORIGINALLY INTENDED TO DO."

SOCIETY DEFINITION (DO NOT USE): "SOMEONE WHO BREAKS INTO COMPUTERS FOR MALICIOUS
PURPOSES."

RICHARD STALLMAN'S DEFINITION: "SOMEONE WHO ENJOYS PLAYFUL CLEVERNESS"

"MAKER MOVEMENT"
'MAKING' BECOMES MAINSTREAM THANKS TO NEW TECHNOLOGIES ENTERING PUB. DOMAIN:
  1. FUSED DEPOSITION MOULDING
  2. ARDUINO

THE ARDUINO
  - ORIGINALLY CALLED 'WIRING'
  - 
"""
